/*
 * Application metadata.
 */
var copyright = 'Copyright (c) 2013 John Newman';

module.exports = {
  version   : 'Reaver 0.0.1',
  copyright : copyright,
  license   : [
      '-----------------------------------------------------------------------------'
    , 'The MIT License (MIT)'
    , ''
    , copyright
    , ''
    , 'Permission is hereby granted, free of charge, to any person obtaining a copy'
    , 'of this software and associated documentation files (the "Software"), to deal'
    , 'in the Software without restriction, including without limitation the rights'
    , 'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell'
    , 'copies of the Software, and to permit persons to whom the Software is'
    , 'furnished to do so, subject to the following conditions:'
    , ''
    , 'The above copyright notice and this permission notice shall be included in'
    , 'all copies or substantial portions of the Software.'
    , ''
    , 'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR'
    , 'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,'
    , 'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE'
    , 'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER'
    , 'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,'
    , 'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN'
    , 'THE SOFTWARE.'
    , '-----------------------------------------------------------------------------'
  ].join('\n'),
  help : [
      ''
    , '  Usage: reaver [action] [options]'
    , ''
    , '  Actions:'
    , ''
    , '    spawn     Creates a new reaver project.'
    , '    server    Launches a local server on port 8888 for viewing and development.'
    , '    build     Compiles a static site.'
    , ''
    , '  Options:'
    , ''
    , '    -v, --version     Display the version of reaver.'
    , '    -h, --help        Display help information.'
    , '    -d, --directory   The directory for spawning/serving/building the project.'
    , '    -n, --name        For use with spawn.  The name for the new project.'
    , '    -p, --port        For use with server. A custom port number to use for serving.'
    , '        --dsh         For use with server. An IP or http hostname of a datastore.'
    , '        --dsp         For use with server. A port for the datastore host.'
    , '        --dst         For use with server. A same-origin ajax path that will trigger'
    , '                      a connection to the datastore.'
    , ''
    , '  Note:'
    , '    If no datastore information is provided when calling server, --dst will default'
    , '    to "/datastore" and the datastore host and port will be automatically set to the'
    , '    default settings of a local couchDB instance. If you are not using a datastore,'
    , '    this will cause no harm.'
    , ''
    , ''
    , '  Examples:'
    , ''
    , '    reaver -v                  Displays the current version.'
    , '    reaver -h                  Displays this help information.'
    , '    reaver spawn               Spawns a new unnamed project in the current dir.'
    , '    reaver spawn -d some/dir   Spawns a new unnamed project in some/dir.'
    , '    reaver spawn -n MySite     Spawns a new project called MySite in the current dir.'
    , '    reaver server              Serves the project in the current dir on port 8888.'
    , '    reaver server -d some/dir  Serves the project in some/dir on port 8888.'
    , '    reaver server -p 8000      Serves the project in the current dir on port 8000.'
    , '    reaver build               Builds a static site from files in the current directory.'
    , '    reaver build -d some/dir   Builds a static site from files in some/dir.'
    , ''
  ].join('\n'),
};